# Generated by Django 5.1.1 on 2024-09-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arriamentos', '0001_initial'),
        ('roupas', '0001_initial'),
        ('tamanhos', '0001_initial'),
        ('tecidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('detalhamento', models.TextField()),
                ('arriamento', models.ManyToManyField(related_name='arriamento', to='arriamentos.arriamento')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupas.roupa')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamanhos.tamanho')),
                ('tecido', models.ManyToManyField(related_name='tecidos', to='tecidos.tecido')),
            ],
        ),
    ]
